AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Application Model template describing your function.
Parameters:
  Repository:
    Type: String
    Description: The GitHub repository to deploy the frontend to
  SecretName:
    Type: String
    Description: The AWS Secrets Manager's secret name with Tavily and OpenAI API keys

Resources:
  GenerateResponse:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/generate_response/
      Description: ''
      MemorySize: 128
      Timeout: 900
      Handler: handler.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      PackageType: Zip
      Environment:
        Variables:
          SECRET_NAME: !Ref SecretName
          REGION_NAME: !Ref AWS::Region
          RATINGS_TABLE_NAME: !Ref UserRatingsTable
          OPENAI_API_KEY: ''
          TAVILY_API_KEY: ''
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${SecretName}*
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
              Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*
            - Effect: Allow
              Action:
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource:
                - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/GenerateResponse:*
            - Effect: Allow
              Action:
                - dynamodb:PutItem
              Resource: !GetAtt UserRatingsTable.Arn
      SnapStart:
        ApplyOn: None
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto
      Events:
        TruthSeekerRestApiGETgenerateresponse:
          Type: Api
          Properties:
            Path: /generate_response/{version}/{language}/{query}
            Method: GET
            RestApiId: !Ref TruthSeekerRestApi

  UserRatingsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: UserRatings
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  TruthSeekerRestApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub
        - ${ResourceName}
        - ResourceName: TruthSeekerRestApi
      StageName: dev
      DefinitionBody:
        openapi: '3.0'
        info: {}
        paths:
          /generate_response/{version}/{language}/{query}:
            get:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GenerateResponse.Arn}/invocations
              responses: {}
          /rate_response:
            post:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${RateResponse.Arn}/invocations
              responses: {}
          /health:
            get:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HealthCheck.Arn}/invocations
              responses: {}
      EndpointConfiguration: REGIONAL
      TracingEnabled: true
      Cors:
        AllowOrigin: '''*'''
        AllowHeaders: '''Content-Type'''
        AllowMethods: '''OPTIONS, POST, GET'''

  HealthCheck:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: HealthCheck
      CodeUri: ./src/health_check
      Handler: handler.lambda_handler
      Runtime: python3.11
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Events:
        TruthSeekerRestApiGEThealth:
          Type: Api
          Properties:
            Path: /health
            Method: GET
            RestApiId: !Ref TruthSeekerRestApi

  HealthCheckLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${HealthCheck}

  TruthSeekerAmplifyApp:
    Type: AWS::Amplify::App
    Properties:
      Name: !Sub ${AWS::StackName}-${AWS::Region}-${AWS::AccountId}
      Repository: !Ref Repository
      BuildSpec: |
        version: 1
        applications:
          - frontend:
              phases:
                preBuild:
                  commands:
                    - npm ci
                build:
                  commands:
                    - npm run build
              artifacts:
                baseDirectory: dist
                files:
                  - '**/*'
              cache:
                paths:
                  - node_modules/**/*
            appRoot: frontend
      AccessToken: '{{resolve:secretsmanager:truth-seeker-github-token}}'
      EnvironmentVariables:
        - Name: AMPLIFY_MONOREPO_APP_ROOT
          Value: frontend
        - Name: VITE_REGION
          Value: !Ref AWS::Region
        - Name: VITE_API_ENDPOINT
          Value: !Sub https://${TruthSeekerRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/dev/

  AmplifyBranch:
    Type: AWS::Amplify::Branch
    Properties:
      BranchName: main
      AppId: !GetAtt TruthSeekerAmplifyApp.AppId
      EnableAutoBuild: true

  RateResponse:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: RateResponse
      CodeUri: ./src/rate_response
      Handler: handler.lambda_handler
      Runtime: python3.11
      MemorySize: 128
      Timeout: 30
      Tracing: Active
      Events:
        TruthSeekerRestApiPOSTrateresponse:
          Type: Api
          Properties:
            Path: /rate_response
            Method: POST
            RestApiId: !Ref TruthSeekerRestApi
      Environment:
        Variables:
          RATINGS_TABLE_NAME: !Ref UserRatingsTable
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:UpdateItem
              Resource: !GetAtt UserRatingsTable.Arn

  RateResponseLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${RateResponse}

Metadata:
  AWS::Composer::Groups:
    Group:
      Label: API
      Members:
        - GenerateResponse
        - RateResponse
        - HealthCheck

Outputs:
  ApiGatewayBaseUrl:
    Value: !Sub https://${TruthSeekerRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/dev/